[package]
name = "password_engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "password_engine"
path = "src/lib.rs"

[dependencies]
regex = "1"
lazy_static = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
phf = "0.11" # for constant-time maps (dictionary)
